"""empty message

Revision ID: 34cb312cb118
Revises: 
Create Date: 2018-10-10 20:23:27.422352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cb312cb118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('requesthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_name', sa.String(length=140), nullable=True),
    sa.Column('volume_name', sa.String(length=140), nullable=True),
    sa.Column('volume_number', sa.String(length=4), nullable=True),
    sa.Column('url', sa.String(length=1800), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requesthistory_series_name'), 'requesthistory', ['series_name'], unique=False)
    op.create_index(op.f('ix_requesthistory_timestamp'), 'requesthistory', ['timestamp'], unique=False)
    op.create_index(op.f('ix_requesthistory_volume_name'), 'requesthistory', ['volume_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requesthistory_volume_name'), table_name='requesthistory')
    op.drop_index(op.f('ix_requesthistory_timestamp'), table_name='requesthistory')
    op.drop_index(op.f('ix_requesthistory_series_name'), table_name='requesthistory')
    op.drop_table('requesthistory')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
