"""empty message

Revision ID: 7ec9dd53f33b
Revises: ffe5c36f5fa1
Create Date: 2018-08-12 00:57:09.697078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec9dd53f33b'
down_revision = 'ffe5c36f5fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_request_history_series_name'), 'request_history', ['series_name'], unique=False)
    op.create_index(op.f('ix_request_history_volume_name'), 'request_history', ['volume_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_history_volume_name'), table_name='request_history')
    op.drop_index(op.f('ix_request_history_series_name'), table_name='request_history')
    # ### end Alembic commands ###
