"""empty message

Revision ID: 9be5819754ce
Revises: 7ec9dd53f33b
Create Date: 2018-08-17 12:46:55.469597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be5819754ce'
down_revision = '7ec9dd53f33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_history', sa.Column('url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_history', 'url')
    # ### end Alembic commands ###
