"""empty message

Revision ID: d0ffa9d2e5ba
Revises: 04e3c6f66b36
Create Date: 2018-09-06 11:32:59.144114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ffa9d2e5ba'
down_revision = '04e3c6f66b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_history', sa.Column('volume_number', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_history', 'volume_number')
    # ### end Alembic commands ###
