"""empty message

Revision ID: ffe5c36f5fa1
Revises: 6d1e52c9b6dc
Create Date: 2018-08-09 09:39:20.292575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe5c36f5fa1'
down_revision = '6d1e52c9b6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_name', sa.String(length=140), nullable=True),
    sa.Column('volume_name', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_history_timestamp'), 'request_history', ['timestamp'], unique=False)
    op.drop_index('ix_request_timestamp', table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('series_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('volume_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_timestamp', 'request', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_request_history_timestamp'), table_name='request_history')
    op.drop_table('request_history')
    # ### end Alembic commands ###
